# This is a basic workflow to help you get started with Actions
name: Dropbox download
on:
  push:
     branches: 
       - master 
  schedule:
   - cron: 0 1/8 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "check if branch exists"
        run: git branch --list Dropbox-refrence | grep -c Dropbox-refrence
      - name: "check"
        if: failure()
        run: echo "does not work"
      - uses: actions/checkout@v2
        with:
          ref: Dropbox-refrence
      - name: "Download form dropbox"
        run: echo todo
      
